### ISSUE TITLE
setInterval is not cleared after unmount 

### ISSUE THREAD

**Issue by Log-of-e** [wtr7/react-loader-quotes#1]
setInterval for quotesInterval DOES properly clear if props "loading" is set to false before unmounting.

  However when using react-router, the component  ReactLoaderQuotes unmounts , if the "loading" props is still set to true the code for quotesInterval still executes and there is a warning in the console:
 >  Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ReactLoaderQuotes component.

  Not a real issue, more of an FYI.

**Comment by wtr7** [comment]
Thanks @Log-of-e! Should be fixed in 1.0.2
